services:
  host1:
    image: vulnerables/web-dvwa:latest
    container_name: host1
    networks:
      untrusted:
        ipv4_address: 172.21.0.10

  host2:
    image: tleemcjr/metasploitable2:latest
    container_name: host2
    command: /bin/bash -c "service ssh start && service apache2 start && tail -f /dev/null"
    networks:
      untrusted:
        ipv4_address: 172.21.0.11

  host3:
    image: ubuntu:jammy
    container_name: host3
    command: tail -f /dev/null
    networks:
      untrusted:
        ipv4_address: 172.21.0.12

  host4:
    image: kalilinux/kali-rolling
    container_name: host4
    command: tail -f /dev/null
    networks:
      untrusted:
        ipv4_address: 172.21.0.13

  host5:
    image: ubuntu:latest
    container_name: host5
    command: tail -f /dev/null
    networks:
      untrusted:
        ipv4_address: 172.21.0.14

  host6:
    image: ubuntu:latest
    container_name: host6
    command: tail -f /dev/null
    networks:
      trusted:
        ipv4_address: 192.168.100.2

networks:
  trusted:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
          gateway: 192.168.100.1

  untrusted:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1
