services:
  host1:
    image: vulnerables/web-dvwa:latest
    container_name: host1
    networks:
      public:
        ipv4_address: 172.21.0.10

  host2:
    image: tleemcjr/metasploitable2:latest
    container_name: host2
    command: /bin/bash -c "service ssh start && service apache2 start && tail -f /dev/null"
    networks:
      public:
        ipv4_address: 172.21.0.11

  host3:
    image: ubuntu
    container_name: host3
    command: tail -f /dev/null
    networks:
      public:
        ipv4_address: 172.21.0.12

  scanner:
    container_name: scanner
    build:
      context: ../Dockerfiles/scanner
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      public:
        ipv4_address: 172.21.0.20
      private:
        ipv4_address: 192.168.100.10

networks:
  private:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
          gateway: 192.168.100.1

  public:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1
